### ISSUE TITLE
Update for ABIv5

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-evmc#3]
https://github.com/ethereum/evmc/commit/a3cb335babe5f675d706c2ba50c4c044c78cd031#diff-8e9caa43721b131d9f7897e2bfd98299

**Comment by mratsim** [comment]
EVMC 5.0 is out: https://github.com/ethereum/evmc/commit/cd435f8f785ec9fd5567734633638bdfd8031bd9

**Comment by mratsim** [comment]
Evmc 5.2 https://github.com/ethereum/evmc/releases/tag/v5.2.0

**Comment by axic** [comment]
Heads up: we're close to releasing ABIv7 for Istanbul support and ABIv8 will have a major redesign regarding storage gas costs :wink:

**Comment by jangko** [comment]
fixed by #5, closing.
